using System;
using System.Xml; 
using System.Xml.Serialization; 
 namespace oval{       [XmlIncludeAttribute(typeof(EntityStateStringType))]
    [XmlIncludeAttribute(typeof(EntityStateInterimFixStateType))]
    [XmlIncludeAttribute(typeof(EntityStateFixInstallationStatusType))]
    [XmlIncludeAttribute(typeof(EntityStateFilesetStateType))]
    [XmlIncludeAttribute(typeof(EntityStateWifiProtocolType))]
    [XmlIncludeAttribute(typeof(EntityStateWifiPairwiseCipherType))]
    [XmlIncludeAttribute(typeof(EntityStateWifiKeyMgmtType))]
    [XmlIncludeAttribute(typeof(EntityStateWifiGroupCipherType))]
    [XmlIncludeAttribute(typeof(EntityStateWifiCurrentStatusType))]
    [XmlIncludeAttribute(typeof(EntityStateWifiAuthAlgorithmType))]
    [XmlIncludeAttribute(typeof(EntityStatePasswordQualityType))]
    [XmlIncludeAttribute(typeof(EntityStateNetworkType))]
    [XmlIncludeAttribute(typeof(EntityStateKeyguardDisabledFeaturesType))]
    [XmlIncludeAttribute(typeof(EntityStateEncryptionStatusType))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPPrivStringType2))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPAuthStringType2))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPSecLevelStringType2))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPVersionStringType2))]
    [XmlIncludeAttribute(typeof(EntityStateMatchType))]
    [XmlIncludeAttribute(typeof(EntityStateApplyServicePolicyType))]
    [XmlIncludeAttribute(typeof(EntityStateInspectionType))]
    [XmlIncludeAttribute(typeof(EntityStateClassMapType))]
    [XmlIncludeAttribute(typeof(EntityStateAccessListInterfaceDirectionType2))]
    [XmlIncludeAttribute(typeof(EntityStateAccessListUseType2))]
    [XmlIncludeAttribute(typeof(EntityStateAccessListIPVersionType2))]
    [XmlIncludeAttribute(typeof(EntityStateSupportLevelType))]
    [XmlIncludeAttribute(typeof(EntityStateClassificationType))]
    [XmlIncludeAttribute(typeof(EntityStateAccessListInterfaceDirectionType1))]
    [XmlIncludeAttribute(typeof(EntityStateAccessListUseType1))]
    [XmlIncludeAttribute(typeof(EntityStateAccessListIPVersionType1))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPPrivStringType1))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPAuthStringType1))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPModeStringType1))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPSecLevelStringType1))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPVersionStringType1))]
    [XmlIncludeAttribute(typeof(EntityStateRoutingAuthTypeStringType1))]
    [XmlIncludeAttribute(typeof(EntityStateRoutingProtocolType1))]
    [XmlIncludeAttribute(typeof(EntityStateSwitchportModeType1))]
    [XmlIncludeAttribute(typeof(EntityStateTrunkEncapType1))]
    [XmlIncludeAttribute(typeof(EntityStateTrunkEncapType))]
    [XmlIncludeAttribute(typeof(EntityStateTrainIdentifierType))]
    [XmlIncludeAttribute(typeof(EntityStateSwitchportModeType))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPPrivStringType))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPAuthStringType))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPModeStringType))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPSecLevelStringType))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPVersionStringType))]
    [XmlIncludeAttribute(typeof(EntityStateRoutingProtocolType))]
    [XmlIncludeAttribute(typeof(EntityStateRoutingAuthTypeStringType))]
    [XmlIncludeAttribute(typeof(EntityStateAccessListUseType))]
    [XmlIncludeAttribute(typeof(EntityStateAccessListIPVersionType))]
    [XmlIncludeAttribute(typeof(EntityStateAccessListInterfaceDirectionType))]
    [XmlIncludeAttribute(typeof(EntityStateProtocolType1))]
    [XmlIncludeAttribute(typeof(EntityStateRpmVerifyResultType))]
    [XmlIncludeAttribute(typeof(EntityStateJunosReleaseTypeType))]
    [XmlIncludeAttribute(typeof(EntityStatePlistTypeType))]
    [XmlIncludeAttribute(typeof(EntityStatePermissionCompareType1))]
    [XmlIncludeAttribute(typeof(EntityStateInterfaceType))]
    [XmlIncludeAttribute(typeof(EntityStateEncryptMethodType))]
    [XmlIncludeAttribute(typeof(EntityStateWaitStatusType))]
    [XmlIncludeAttribute(typeof(EntityStateXinetdTypeStatusType))]
    [XmlIncludeAttribute(typeof(EntityStateRoutingTableFlagsType))]
    [XmlIncludeAttribute(typeof(EntityStateGconfTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateEndpointType))]
    [XmlIncludeAttribute(typeof(EntityStateCapabilityType))]
    [XmlIncludeAttribute(typeof(EntityStateUrlZoneType))]
    [XmlIncludeAttribute(typeof(EntityStatePolicyFeatureStateType))]
    [XmlIncludeAttribute(typeof(EntityStatePolicyRoleType))]
    [XmlIncludeAttribute(typeof(EntityStateTraceSeverityType))]
    [XmlIncludeAttribute(typeof(EntityStateEventSeverityType))]
    [XmlIncludeAttribute(typeof(EntityStateLDOMRoleType))]
    [XmlIncludeAttribute(typeof(EntityStateV12NEnvType))]
    [XmlIncludeAttribute(typeof(EntityStateSmfServiceStateType))]
    [XmlIncludeAttribute(typeof(EntityStatePublisherTypeType))]
    [XmlIncludeAttribute(typeof(EntityStatePermissionCompareType))]
    [XmlIncludeAttribute(typeof(EntityStateClientUUIDType))]
    [XmlIncludeAttribute(typeof(EntityStateUserRightType))]
    [XmlIncludeAttribute(typeof(EntityStateWindowsViewType1))]
    [XmlIncludeAttribute(typeof(EntityStateCmdletVerbType))]
    [XmlIncludeAttribute(typeof(EntityStateGUIDType))]
    [XmlIncludeAttribute(typeof(EntityStateSystemMetricIndexType))]
    [XmlIncludeAttribute(typeof(EntityStateSharedResourceTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateServiceTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateServiceStartTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateServiceCurrentStateType))]
    [XmlIncludeAttribute(typeof(EntityStateServiceControlsAcceptedType))]
    [XmlIncludeAttribute(typeof(EntityStateRegistryTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateRegistryHiveType))]
    [XmlIncludeAttribute(typeof(EntityStateProtocolType))]
    [XmlIncludeAttribute(typeof(EntityStatePeSubsystemType))]
    [XmlIncludeAttribute(typeof(EntityStatePeTargetMachineType))]
    [XmlIncludeAttribute(typeof(EntityStateNTUserAccountTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateNamingContextType))]
    [XmlIncludeAttribute(typeof(EntityStateFileAttributeType))]
    [XmlIncludeAttribute(typeof(EntityStateFileTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateInterfaceTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateDriveTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateAuditType))]
    [XmlIncludeAttribute(typeof(EntityStateAdstypeType))]
    [XmlIncludeAttribute(typeof(EntityStateAddrTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateWindowsViewType))]
    [XmlIncludeAttribute(typeof(EntityStateLdaptypeType))]
    [XmlIncludeAttribute(typeof(EntityStateVariableRefType))]
    [XmlIncludeAttribute(typeof(EntityStateHashTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateFamilyType))]
    [XmlIncludeAttribute(typeof(EntityStateEngineType))]
    [XmlIncludeAttribute(typeof(EntityStateIOSVersionType))]
    [XmlIncludeAttribute(typeof(EntityStateFileSetRevisionType))]
    [XmlIncludeAttribute(typeof(EntityStateVersionType))]
    [XmlIncludeAttribute(typeof(EntityStateDebianEVRStringType))]
    [XmlIncludeAttribute(typeof(EntityStateEVRStringType))]
    [XmlIncludeAttribute(typeof(EntityStateIntType))]
    [XmlIncludeAttribute(typeof(EntityStateFloatType))]
    [XmlIncludeAttribute(typeof(EntityStateBoolType))]
    [XmlIncludeAttribute(typeof(EntityStateBinaryType))]
    [XmlIncludeAttribute(typeof(EntityStateAnySimpleType))]
    [XmlIncludeAttribute(typeof(EntityStateIPAddressStringType))]
    [XmlIncludeAttribute(typeof(EntityStateIPAddressType))]
    [SerializableAttribute]
    [XmlTypeAttribute(Namespace="http://oval.mitre.org/XMLSchema/oval-definitions-5")]

    public abstract class EntityStateSimpleBaseType : EntitySimpleBaseType {

        [XmlAttribute]
        public CheckEnumeration entity_check { get { return entity_checkField.Value; } set { entity_checkField=value; } }
        [XmlIgnore]
        public CheckEnumeration? entity_checkField { get; set; }
        public bool entity_checkSpecified  => entity_checkField.HasValue;

        [XmlAttribute]
        public ExistenceEnumeration check_existence { get { return check_existenceField.Value; } set { check_existenceField=value; } }

        [XmlIgnore]
        public ExistenceEnumeration? check_existenceField { get; set; }
        public bool check_existenceSpecified => check_existenceField.HasValue;


        public EntityStateSimpleBaseType() {
            //this.entity_checkField = CheckEnumeration.all;
            //this.check_existenceField = ExistenceEnumeration.at_least_one_exists;
        }
    }

}

