using System;
using System.Xml; 
using System.Xml.Serialization; 
 namespace oval{       [SerializableAttribute]
    [XmlTypeAttribute(AnonymousType=true, Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5")]
    [XmlRootAttribute(Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5", IsNullable=false)]
    public class oval_system_characteristics {
        private GeneratorType generatorField;
        private SystemInfoType system_infoField;
        private ObjectType2[] collected_objectsField;
        private ItemType[] system_dataField;
        private SignatureType signatureField;
        public GeneratorType generator {
            get {
                return this.generatorField;
            }
            set {
                this.generatorField = value;
            }
        }
        public SystemInfoType system_info {
            get {
                return this.system_infoField;
            }
            set {
                this.system_infoField = value;
            }
        }
        [XmlArrayItemAttribute("object", IsNullable=false)]
        public ObjectType2[] collected_objects {
            get {
                return this.collected_objectsField;
            }
            set {
                this.collected_objectsField = value;
            }
        }
        [XmlArrayItemAttribute("item", IsNullable=false)]
        [XmlArrayItem (typeof(family_item                             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#independent")]
        [XmlArrayItem (typeof(filehash_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#independent")]
        [XmlArrayItem (typeof(filehash58_item                         ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#independent")]
        [XmlArrayItem (typeof(environmentvariable_item                ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#independent")]
        [XmlArrayItem (typeof(environmentvariable58_item              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#independent")]
        [XmlArrayItem (typeof(ldap_item                               ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#independent")]
        [XmlArrayItem (typeof(ldap57_item                             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#independent")]
        [XmlArrayItem (typeof(sql_item                                ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#independent")]
        [XmlArrayItem (typeof(sql57_item                              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#independent")]
        [XmlArrayItem (typeof(textfilecontent_item                    ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#independent")]
        [XmlArrayItem (typeof(variable_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#independent")]
        [XmlArrayItem (typeof(xmlfilecontent_item                     ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#independent")]
        [XmlArrayItem (typeof(accesstoken_item                        ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(activedirectory_item                    ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(activedirectory57_item                  ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(auditeventpolicy_item                   ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(auditeventpolicysubcategories_item      ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(cmdlet_item                             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(dnscache_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(file_item                               ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(fileauditedpermissions_item             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(fileeffectiverights_item                ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(group_item                              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(group_sid_item                          ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(interface_item                          ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(junction_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(license_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(lockoutpolicy_item                      ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(metabase_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(ntuser_item                             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(passwordpolicy_item                     ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(peheader_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(port_item                               ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(printereffectiverights_item             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(process_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(registry_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(regkeyauditedpermissions_item           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(regkeyeffectiverights_item              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(service_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(serviceeffectiverights_item             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(sharedresource_item                     ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(sharedresourceauditedpermissions_item   ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(sharedresourceeffectiverights_item      ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(sid_item                                ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(sid_sid_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(systemmetric_item                       ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(uac_item                                ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(user_item                               ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(user_sid_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(userright_item                          ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(volume_item                             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(wmi_item                                ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(wmi57_item                              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(wuaupdatesearcher_item                  ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#windows")]
        [XmlArrayItem (typeof(facet_item                              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#solaris")]
        [XmlArrayItem (typeof(image_item                              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#solaris")]
        [XmlArrayItem (typeof(isainfo_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#solaris")]
        [XmlArrayItem (typeof(ndd_item                                ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#solaris")]
        [XmlArrayItem (typeof(package_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#solaris")]
        [XmlArrayItem (typeof(package511_item                         ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#solaris")]
        [XmlArrayItem (typeof(packageavoidlist_item                   ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#solaris")]
        [XmlArrayItem (typeof(packagecheck_item                       ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#solaris")]
        [XmlArrayItem (typeof(packagefreezelist_item                  ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#solaris")]
        [XmlArrayItem (typeof(packagepublisher_item                   ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#solaris")]
        [XmlArrayItem (typeof(patch_item                              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#solaris")]
        [XmlArrayItem (typeof(smf_item                                ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#solaris")]
        [XmlArrayItem (typeof(smfproperty_item                        ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#solaris")]
        [XmlArrayItem (typeof(variant_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#solaris")]
        [XmlArrayItem (typeof(virtualizationinfo_item                 ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#solaris")]
        [XmlArrayItem (typeof(spwebapplication_item                   ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#sharepoint")]
        [XmlArrayItem (typeof(spgroup_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#sharepoint")]
        [XmlArrayItem (typeof(spweb_item                              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#sharepoint")]
        [XmlArrayItem (typeof(splist_item                             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#sharepoint")]
        [XmlArrayItem (typeof(spantivirussettings_item                ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#sharepoint")]
        [XmlArrayItem (typeof(spsiteadministration_item               ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#sharepoint")]
        [XmlArrayItem (typeof(spsite_item                             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#sharepoint")]
        [XmlArrayItem (typeof(spcrawlrule_item                        ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#sharepoint")]
        [XmlArrayItem (typeof(spjobdefinition_item                    ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#sharepoint")]
        [XmlArrayItem (typeof(spjobdefinition510_item                 ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#sharepoint")]
        [XmlArrayItem (typeof(bestbet_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#sharepoint")]
        [XmlArrayItem (typeof(infopolicycoll_item                     ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#sharepoint")]
        [XmlArrayItem (typeof(spdiagnosticsservice_item               ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#sharepoint")]
        [XmlArrayItem (typeof(spdiagnosticslevel_item                 ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#sharepoint")]
        [XmlArrayItem (typeof(sppolicyfeature_item                    ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#sharepoint")]
        [XmlArrayItem (typeof(sppolicy_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#sharepoint")]
        [XmlArrayItem (typeof(dnscache_item1                          ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#unix",ElementName="dnscache_item")]
        [XmlArrayItem (typeof(file_item1                              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#unix",ElementName="file_item")]
        [XmlArrayItem (typeof(fileextendedattribute_item              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#unix")]
        [XmlArrayItem (typeof(gconf_item                              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#unix")]
        [XmlArrayItem (typeof(inetd_item                              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#unix")]
        [XmlArrayItem (typeof(interface_item1                         ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#unix",ElementName="interface_item")]
        [XmlArrayItem (typeof(password_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#unix")]
        [XmlArrayItem (typeof(process_item1                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#unix",ElementName="process_item")]
        [XmlArrayItem (typeof(process58_item                          ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#unix")]
        [XmlArrayItem (typeof(routingtable_item                       ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#unix")]
        [XmlArrayItem (typeof(runlevel_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#unix")]
        [XmlArrayItem (typeof(sccs_item                               ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#unix")]
        [XmlArrayItem (typeof(shadow_item                             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#unix")]
        [XmlArrayItem (typeof(symlink_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#unix")]
        [XmlArrayItem (typeof(sysctl_item                             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#unix")]
        [XmlArrayItem (typeof(uname_item                              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#unix")]
        [XmlArrayItem (typeof(xinetd_item                             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#unix")]
        [XmlArrayItem (typeof(line_item                               ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#pixos")]
        [XmlArrayItem (typeof(version_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#pixos")]
        [XmlArrayItem (typeof(accountinfo_item                        ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#macos")]
        [XmlArrayItem (typeof(authorizationdb_item                    ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#macos")]
        [XmlArrayItem (typeof(corestorage_item                        ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#macos")]
        [XmlArrayItem (typeof(diskutil_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#macos")]
        [XmlArrayItem (typeof(gatekeeper_item                         ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#macos")]
        [XmlArrayItem (typeof(inetlisteningserver_item                ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#macos")]
        [XmlArrayItem (typeof(inetlisteningserver510_item             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#macos")]
        [XmlArrayItem (typeof(keychain_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#macos")]
        [XmlArrayItem (typeof(launchd_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#macos")]
        [XmlArrayItem (typeof(nvram_item                              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#macos")]
        [XmlArrayItem (typeof(plist_item                              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#macos")]
        [XmlArrayItem (typeof(plist511_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#macos")]
        [XmlArrayItem (typeof(pwpolicy_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#macos")]
        [XmlArrayItem (typeof(pwpolicy59_item                         ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#macos")]
        [XmlArrayItem (typeof(rlimit_item                             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#macos")]
        [XmlArrayItem (typeof(softwareupdate_item                     ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#macos")]
        [XmlArrayItem (typeof(systemprofiler_item                     ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#macos")]
        [XmlArrayItem (typeof(systemsetup_item                        ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#macos")]
        [XmlArrayItem (typeof(config_item                             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#netconf")]
        [XmlArrayItem (typeof(xml_config_item                         ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#junos")]
        [XmlArrayItem (typeof(show_item                               ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#junos")]
        [XmlArrayItem (typeof(version_item1                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#junos",ElementName="version_item")]
        [XmlArrayItem (typeof(xml_show_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#junos")]
        [XmlArrayItem (typeof(apparmorstatus_item                     ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#linux")]
        [XmlArrayItem (typeof(dpkginfo_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#linux")]
        [XmlArrayItem (typeof(iflisteners_item                        ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#linux")]
        [XmlArrayItem (typeof(inetlisteningserver_item1               ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#linux",ElementName="inetlisteningserver_item")]
        [XmlArrayItem (typeof(partition_item                          ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#linux")]
        [XmlArrayItem (typeof(rpminfo_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#linux")]
        [XmlArrayItem (typeof(rpmverify_item                          ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#linux")]
        [XmlArrayItem (typeof(rpmverifyfile_item                      ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#linux")]
        [XmlArrayItem (typeof(rpmverifypackage_item                   ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#linux")]
        [XmlArrayItem (typeof(selinuxboolean_item                     ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#linux")]
        [XmlArrayItem (typeof(selinuxsecuritycontext_item             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#linux")]
        [XmlArrayItem (typeof(slackwarepkginfo_item                   ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#linux")]
        [XmlArrayItem (typeof(systemdunitdependency_item              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#linux")]
        [XmlArrayItem (typeof(systemdunitproperty_item                ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#linux")]
        [XmlArrayItem (typeof(acl_item                                ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios")]
        [XmlArrayItem (typeof(bgpneighbor_item                        ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios")]
        [XmlArrayItem (typeof(global_item                             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios")]
        [XmlArrayItem (typeof(interface_item2                         ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios",ElementName="interface_item")]
        [XmlArrayItem (typeof(line_item1                              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios",ElementName="line_item")]
        [XmlArrayItem (typeof(router_item                             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios")]
        [XmlArrayItem (typeof(routingprotocolauthintf_item            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios")]
        [XmlArrayItem (typeof(section_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios")]
        [XmlArrayItem (typeof(snmp_item                               ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios")]
        [XmlArrayItem (typeof(snmpcommunity_item                      ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios")]
        [XmlArrayItem (typeof(snmpgroup_item                          ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios")]
        [XmlArrayItem (typeof(snmphost_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios")]
        [XmlArrayItem (typeof(snmpuser_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios")]
        [XmlArrayItem (typeof(snmpview_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios")]
        [XmlArrayItem (typeof(tclsh_item                              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios")]
        [XmlArrayItem (typeof(version_item2                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#ios",ElementName="version_item")]
        [XmlArrayItem (typeof(global_item1                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#iosxe",ElementName="global_item")]
        [XmlArrayItem (typeof(line_item2                              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#iosxe",ElementName="line_item")]
        [XmlArrayItem (typeof(version_item3                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#iosxe",ElementName="version_item")]
        [XmlArrayItem (typeof(section_item1                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#iosxe",ElementName="section_item")]
        [XmlArrayItem (typeof(interface_item3                         ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#iosxe",ElementName="interface_item")]
        [XmlArrayItem (typeof(router_item1                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#iosxe",ElementName="router_item")]
        [XmlArrayItem (typeof(bgpneighbor_item1                       ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#iosxe",ElementName="bgpneighbor_item")]
        [XmlArrayItem (typeof(routingprotocolauthintf_item1           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#iosxe",ElementName="routingprotocolauthintf_item")]
        [XmlArrayItem (typeof(acl_item1                               ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#iosxe",ElementName="acl_item")]
        [XmlArrayItem (typeof(snmphost_item1                          ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#iosxe",ElementName="snmphost_item")]
        [XmlArrayItem (typeof(snmpcommunity_item1                     ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#iosxe",ElementName="snmpcommunity_item")]
        [XmlArrayItem (typeof(snmpuser_item1                          ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#iosxe",ElementName="snmpuser_item")]
        [XmlArrayItem (typeof(snmpgroup_item1                         ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#iosxe",ElementName="snmpgroup_item")]
        [XmlArrayItem (typeof(snmpview_item1                          ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#iosxe",ElementName="snmpview_item")]
        [XmlArrayItem (typeof(line_item3                              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#catos",ElementName="line_item")]
        [XmlArrayItem (typeof(module_item                             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#catos")]
        [XmlArrayItem (typeof(version_item4                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#catos",ElementName="version_item")]
        [XmlArrayItem (typeof(patch_item1                             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#esx",ElementName="patch_item")]
        [XmlArrayItem (typeof(version_item5                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#esx",ElementName="version_item")]
        [XmlArrayItem (typeof(visdkmanagedobject_item                 ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#esx")]
        [XmlArrayItem (typeof(portinfo_item                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#freebsd")]
        [XmlArrayItem (typeof(getconf_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#hpux")]
        [XmlArrayItem (typeof(ndd_item1                               ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#hpux",ElementName="ndd_item")]
        [XmlArrayItem (typeof(patch_item2                             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#hpux",ElementName="patch_item")]
        [XmlArrayItem (typeof(swlist_item                             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#hpux")]
        [XmlArrayItem (typeof(trusted_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#hpux")]
        [XmlArrayItem (typeof(acl_item2                               ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#asa",ElementName="acl_item")]
        [XmlArrayItem (typeof(class_map_item                          ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#asa")]
        [XmlArrayItem (typeof(interface_item4                         ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#asa",ElementName="interface_item")]
        [XmlArrayItem (typeof(line_item4                              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#asa",ElementName="line_item")]
        [XmlArrayItem (typeof(policy_map_item                         ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#asa")]
        [XmlArrayItem (typeof(service_policy_item                     ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#asa")]
        [XmlArrayItem (typeof(snmp_host_item                          ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#asa")]
        [XmlArrayItem (typeof(snmp_user_item                          ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#asa")]
        [XmlArrayItem (typeof(snmp_group_item                         ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#asa")]
        [XmlArrayItem (typeof(tcp_map_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#asa")]
        [XmlArrayItem (typeof(version_item6                           ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#asa",ElementName="version_item")]
        [XmlArrayItem (typeof(appmanager_item                         ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#android")]
        [XmlArrayItem (typeof(bluetooth_item                          ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#android")]
        [XmlArrayItem (typeof(camera_item                             ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#android")]
        [XmlArrayItem (typeof(certificate_item                        ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#android")]
        [XmlArrayItem (typeof(devicesettings_item                     ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#android")]
        [XmlArrayItem (typeof(encryption_item                         ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#android")]
        [XmlArrayItem (typeof(locationservice_item                    ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#android")]
        [XmlArrayItem (typeof(network_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#android")]
        [XmlArrayItem (typeof(password_item1                          ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#android",ElementName="password_item")]
        [XmlArrayItem (typeof(systemdetails_item                      ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#android")]
        [XmlArrayItem (typeof(wifi_item                               ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#android")]
        [XmlArrayItem (typeof(wifinetwork_item                        ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#android")]
        [XmlArrayItem (typeof(telephony_item                          ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#android")]
        [XmlArrayItem (typeof(httpd_item                              ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#apache")]
        [XmlArrayItem (typeof(globalrestrictions_item                 ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#apple_ios")]
        [XmlArrayItem (typeof(passcodepolicy_item                     ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#apple_ios")]
        [XmlArrayItem (typeof(profile_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#apple_ios")]
        [XmlArrayItem (typeof(interim_fix_item                        ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#aix")]
        [XmlArrayItem (typeof(fileset_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#aix")]
        [XmlArrayItem (typeof(fix_item                                ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#aix")]
        [XmlArrayItem (typeof(no_item                                 ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#aix")]
        [XmlArrayItem (typeof(oslevel_item                            ),Namespace="http://oval.mitre.org/XMLSchema/oval-system-characteristics-5#aix")]
        public ItemType[] system_data {
            get {
                return this.system_dataField;
            }
            set {
                this.system_dataField = value;
            }
        }
        [XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public SignatureType Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
    }

}

