using System;
using System.Xml; 
using System.Xml.Serialization; 
 namespace oval{       [XmlIncludeAttribute(typeof(EntityStateSimpleBaseType))]
    [XmlIncludeAttribute(typeof(EntityStateStringType))]
    [XmlIncludeAttribute(typeof(EntityStateInterimFixStateType))]
    [XmlIncludeAttribute(typeof(EntityStateFixInstallationStatusType))]
    [XmlIncludeAttribute(typeof(EntityStateFilesetStateType))]
    [XmlIncludeAttribute(typeof(EntityStateWifiProtocolType))]
    [XmlIncludeAttribute(typeof(EntityStateWifiPairwiseCipherType))]
    [XmlIncludeAttribute(typeof(EntityStateWifiKeyMgmtType))]
    [XmlIncludeAttribute(typeof(EntityStateWifiGroupCipherType))]
    [XmlIncludeAttribute(typeof(EntityStateWifiCurrentStatusType))]
    [XmlIncludeAttribute(typeof(EntityStateWifiAuthAlgorithmType))]
    [XmlIncludeAttribute(typeof(EntityStatePasswordQualityType))]
    [XmlIncludeAttribute(typeof(EntityStateNetworkType))]
    [XmlIncludeAttribute(typeof(EntityStateKeyguardDisabledFeaturesType))]
    [XmlIncludeAttribute(typeof(EntityStateEncryptionStatusType))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPPrivStringType2))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPAuthStringType2))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPSecLevelStringType2))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPVersionStringType2))]
    [XmlIncludeAttribute(typeof(EntityStateMatchType))]
    [XmlIncludeAttribute(typeof(EntityStateApplyServicePolicyType))]
    [XmlIncludeAttribute(typeof(EntityStateInspectionType))]
    [XmlIncludeAttribute(typeof(EntityStateClassMapType))]
    [XmlIncludeAttribute(typeof(EntityStateAccessListInterfaceDirectionType2))]
    [XmlIncludeAttribute(typeof(EntityStateAccessListUseType2))]
    [XmlIncludeAttribute(typeof(EntityStateAccessListIPVersionType2))]
    [XmlIncludeAttribute(typeof(EntityStateSupportLevelType))]
    [XmlIncludeAttribute(typeof(EntityStateClassificationType))]
    [XmlIncludeAttribute(typeof(EntityStateAccessListInterfaceDirectionType1))]
    [XmlIncludeAttribute(typeof(EntityStateAccessListUseType1))]
    [XmlIncludeAttribute(typeof(EntityStateAccessListIPVersionType1))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPPrivStringType1))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPAuthStringType1))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPModeStringType1))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPSecLevelStringType1))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPVersionStringType1))]
    [XmlIncludeAttribute(typeof(EntityStateRoutingAuthTypeStringType1))]
    [XmlIncludeAttribute(typeof(EntityStateRoutingProtocolType1))]
    [XmlIncludeAttribute(typeof(EntityStateSwitchportModeType1))]
    [XmlIncludeAttribute(typeof(EntityStateTrunkEncapType1))]
    [XmlIncludeAttribute(typeof(EntityStateTrunkEncapType))]
    [XmlIncludeAttribute(typeof(EntityStateTrainIdentifierType))]
    [XmlIncludeAttribute(typeof(EntityStateSwitchportModeType))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPPrivStringType))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPAuthStringType))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPModeStringType))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPSecLevelStringType))]
    [XmlIncludeAttribute(typeof(EntityStateSNMPVersionStringType))]
    [XmlIncludeAttribute(typeof(EntityStateRoutingProtocolType))]
    [XmlIncludeAttribute(typeof(EntityStateRoutingAuthTypeStringType))]
    [XmlIncludeAttribute(typeof(EntityStateAccessListUseType))]
    [XmlIncludeAttribute(typeof(EntityStateAccessListIPVersionType))]
    [XmlIncludeAttribute(typeof(EntityStateAccessListInterfaceDirectionType))]
    [XmlIncludeAttribute(typeof(EntityStateProtocolType1))]
    [XmlIncludeAttribute(typeof(EntityStateRpmVerifyResultType))]
    [XmlIncludeAttribute(typeof(EntityStateJunosReleaseTypeType))]
    [XmlIncludeAttribute(typeof(EntityStatePlistTypeType))]
    [XmlIncludeAttribute(typeof(EntityStatePermissionCompareType1))]
    [XmlIncludeAttribute(typeof(EntityStateInterfaceType))]
    [XmlIncludeAttribute(typeof(EntityStateEncryptMethodType))]
    [XmlIncludeAttribute(typeof(EntityStateWaitStatusType))]
    [XmlIncludeAttribute(typeof(EntityStateXinetdTypeStatusType))]
    [XmlIncludeAttribute(typeof(EntityStateRoutingTableFlagsType))]
    [XmlIncludeAttribute(typeof(EntityStateGconfTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateEndpointType))]
    [XmlIncludeAttribute(typeof(EntityStateCapabilityType))]
    [XmlIncludeAttribute(typeof(EntityStateUrlZoneType))]
    [XmlIncludeAttribute(typeof(EntityStatePolicyFeatureStateType))]
    [XmlIncludeAttribute(typeof(EntityStatePolicyRoleType))]
    [XmlIncludeAttribute(typeof(EntityStateTraceSeverityType))]
    [XmlIncludeAttribute(typeof(EntityStateEventSeverityType))]
    [XmlIncludeAttribute(typeof(EntityStateLDOMRoleType))]
    [XmlIncludeAttribute(typeof(EntityStateV12NEnvType))]
    [XmlIncludeAttribute(typeof(EntityStateSmfServiceStateType))]
    [XmlIncludeAttribute(typeof(EntityStatePublisherTypeType))]
    [XmlIncludeAttribute(typeof(EntityStatePermissionCompareType))]
    [XmlIncludeAttribute(typeof(EntityStateClientUUIDType))]
    [XmlIncludeAttribute(typeof(EntityStateUserRightType))]
    [XmlIncludeAttribute(typeof(EntityStateWindowsViewType1))]
    [XmlIncludeAttribute(typeof(EntityStateCmdletVerbType))]
    [XmlIncludeAttribute(typeof(EntityStateGUIDType))]
    [XmlIncludeAttribute(typeof(EntityStateSystemMetricIndexType))]
    [XmlIncludeAttribute(typeof(EntityStateSharedResourceTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateServiceTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateServiceStartTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateServiceCurrentStateType))]
    [XmlIncludeAttribute(typeof(EntityStateServiceControlsAcceptedType))]
    [XmlIncludeAttribute(typeof(EntityStateRegistryTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateRegistryHiveType))]
    [XmlIncludeAttribute(typeof(EntityStateProtocolType))]
    [XmlIncludeAttribute(typeof(EntityStatePeSubsystemType))]
    [XmlIncludeAttribute(typeof(EntityStatePeTargetMachineType))]
    [XmlIncludeAttribute(typeof(EntityStateNTUserAccountTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateNamingContextType))]
    [XmlIncludeAttribute(typeof(EntityStateFileAttributeType))]
    [XmlIncludeAttribute(typeof(EntityStateFileTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateInterfaceTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateDriveTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateAuditType))]
    [XmlIncludeAttribute(typeof(EntityStateAdstypeType))]
    [XmlIncludeAttribute(typeof(EntityStateAddrTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateWindowsViewType))]
    [XmlIncludeAttribute(typeof(EntityStateLdaptypeType))]
    [XmlIncludeAttribute(typeof(EntityStateVariableRefType))]
    [XmlIncludeAttribute(typeof(EntityStateHashTypeType))]
    [XmlIncludeAttribute(typeof(EntityStateFamilyType))]
    [XmlIncludeAttribute(typeof(EntityStateEngineType))]
    [XmlIncludeAttribute(typeof(EntityStateIOSVersionType))]
    [XmlIncludeAttribute(typeof(EntityStateFileSetRevisionType))]
    [XmlIncludeAttribute(typeof(EntityStateVersionType))]
    [XmlIncludeAttribute(typeof(EntityStateDebianEVRStringType))]
    [XmlIncludeAttribute(typeof(EntityStateEVRStringType))]
    [XmlIncludeAttribute(typeof(EntityStateIntType))]
    [XmlIncludeAttribute(typeof(EntityStateFloatType))]
    [XmlIncludeAttribute(typeof(EntityStateBoolType))]
    [XmlIncludeAttribute(typeof(EntityStateBinaryType))]
    [XmlIncludeAttribute(typeof(EntityStateAnySimpleType))]
    [XmlIncludeAttribute(typeof(EntityStateIPAddressStringType))]
    [XmlIncludeAttribute(typeof(EntityStateIPAddressType))]
    [XmlIncludeAttribute(typeof(EntityObjectVersionType))]
    [XmlIncludeAttribute(typeof(EntityObjectStringType))]
    [XmlIncludeAttribute(typeof(EntityObjectAccessListIPVersionType2))]
    [XmlIncludeAttribute(typeof(EntityObjectRoutingProtocolType1))]
    [XmlIncludeAttribute(typeof(EntityObjectAccessListIPVersionType1))]
    [XmlIncludeAttribute(typeof(EntityObjectRoutingProtocolType))]
    [XmlIncludeAttribute(typeof(EntityObjectAccessListIPVersionType))]
    [XmlIncludeAttribute(typeof(EntityStateDataTypeType))]
    [XmlIncludeAttribute(typeof(EntityObjectDataTypeType))]
    [XmlIncludeAttribute(typeof(EntityObjectUrlZoneType))]
    [XmlIncludeAttribute(typeof(EntityObjectPublisherTypeType))]
    [XmlIncludeAttribute(typeof(EntityObjectUserRightType))]
    [XmlIncludeAttribute(typeof(EntityObjectCmdletVerbType))]
    [XmlIncludeAttribute(typeof(EntityObjectGUIDType))]
    [XmlIncludeAttribute(typeof(EntityObjectSystemMetricIndexType))]
    [XmlIncludeAttribute(typeof(EntityObjectRegistryHiveType))]
    [XmlIncludeAttribute(typeof(EntityObjectProtocolType))]
    [XmlIncludeAttribute(typeof(EntityObjectNamingContextType))]
    [XmlIncludeAttribute(typeof(EntityObjectVariableRefType))]
    [XmlIncludeAttribute(typeof(EntityObjectHashTypeType))]
    [XmlIncludeAttribute(typeof(EntityObjectEngineType))]
    [XmlIncludeAttribute(typeof(EntityObjectIntType))]
    [XmlIncludeAttribute(typeof(EntityObjectFloatType))]
    [XmlIncludeAttribute(typeof(EntityObjectBoolType))]
    [XmlIncludeAttribute(typeof(EntityObjectBinaryType))]
    [XmlIncludeAttribute(typeof(EntityObjectAnySimpleType))]
    [XmlIncludeAttribute(typeof(EntityObjectIPAddressStringType))]
    [XmlIncludeAttribute(typeof(EntityObjectIPAddressType))]
    [SerializableAttribute]
    [XmlTypeAttribute(Namespace="http://oval.mitre.org/XMLSchema/oval-definitions-5")]
    public abstract class EntitySimpleBaseType {
        [XmlAttribute]
        public string datatype           { get { return this.datatypeField; } set { this.datatypeField = value; } }
        [XmlIgnore]
        public string datatypeField      { get; set; }
        public bool   datatypeSpecified  { get { if(null==this.datatypeField) return false; return true; } }

        [XmlAttribute]
        public OperationEnumeration operation {get {return this.operationField.Value;}set {this.operationField = value;}}
        [XmlIgnore]
        public OperationEnumeration? operationField       { get; set; }
        public bool operationSpecified=>operationField.HasValue;


        [XmlAttribute]
        public bool mask                { get { return this.maskField.Value; } set { this.maskField = value; } }
        [XmlIgnore]
        public bool? maskField          { get; set; }
        public bool maskSpecified=>maskField.HasValue;

        [XmlAttribute]
        public string var_ref           { get { return this.var_refField; } set { this.var_refField = value; } }
        [XmlIgnore]
        public string var_refField      { get; set; }
        public bool   var_refSpecified  { get { if(null==this.var_refField) return false; return true; } }


        [XmlAttribute]
        public CheckEnumeration var_check { get { return this.var_checkField.Value; } set { this.var_checkField = value; } }
        [XmlIgnore]
        public CheckEnumeration? var_checkField       { get; set; }
        public bool var_checkSpecified=>var_checkField.HasValue;

        [XmlText]
        public string Value { get { return this.valueField; } set { this.valueField = value; } }    
        [XmlIgnore]
        public string valueField;
        public bool   valueFieldSpecified  { get { if(null==this.valueField) return false; return true; } }

    }

}

